# Project
version=1.1.2
group=org.infernalstudios.celesteconfig
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Celestial Configuration
mod_author=Infernal Studios
mod_id=celesteconfig
license=Apache License 2.0
credits=LudoCrypt - Developer, tinytransfem - Maintainer, evanbones - Maintainer
description=Celestial Configuration is a mod that allows one to change the size of the sun and moon to whatever size you wish!
minecraft_version_range=[1.20.1, 1.20.2)

# Parchment
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Optional Dependencies
cloth_config_version=11.1.118
mod_menu_version=7.2.2

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
