# Project
version=1.1.2
group=org.infernalstudios.celesteconfig
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Celestial Configuration
mod_author=Infernal Studios
mod_id=celesteconfig
license=Apache License 2.0
credits=LudoCrypt - Developer \ntinytransfem - Maintainer \nevanbones - Maintainer
description=Celestial Configuration is a mod that allows one to change the size of the sun and moon to whatever size you wish!
minecraft_version_range=[1.21.1, 1.21.2)

neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.11.10

# Optional Dependencies
cloth_config_version=15.0.140
mod_menu_version=11.0.3

# Fabric
fabric_version=0.116.6+1.21.1
fabric_loader_version=0.16.9

# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false